git:
  remote:
    upstream: 'mongodb/docs-commandline-tools'
    tools: 'mongodb/docs-tools'
project:
  name: 'docs-commandline-tools'
  tag: 'docs-commandline-tools'
  url: 'https://docs.mongodb.com/docs-commandline-tools'
  title: 'MongoDB Commandline Tools'
  branched: false
version:
  release: '1.0'
  branch: 'master'
system:
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'errors.yaml'
    - 'sphinx_local.yaml'
    - 'robots.yaml'
    - 'manpages.yaml'
    - 'integration.yaml'
#   - 'jira.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...
