project: 'docs-commandline-tools'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'mms-cloud'
  sitename: 'MongoDB Commandline Tools'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  repo: 'docs'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'pagenav.html'
...
